# Generated by Django 5.2.5 on 2026-02-09 13:09

import api.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the user",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User's email address (used for login)",
                        max_length=255,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="Unique username (8-16 chars, must start with letter, case-insensitive)",
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                8, message="Username must be at least 8 characters long"
                            ),
                            django.core.validators.MaxLengthValidator(
                                16, message="Username must not exceed 16 characters"
                            ),
                            api.models.validate_username,
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Hashed password",
                        max_length=128,
                        verbose_name="password",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="User's first name",
                        max_length=50,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="User's last name",
                        max_length=50,
                        verbose_name="last name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="User's phone number (7-15 digits)",
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[api.models.validate_phone_number],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="User's biography or description",
                        max_length=500,
                        verbose_name="biography",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="User's profile image",
                        null=True,
                        upload_to="profile_images/",
                        verbose_name="profile image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the user account was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the user account was last updated",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the admin site",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the specialization",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the specialization (e.g., 'Backend Development')",
                        max_length=100,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the specialization",
                        max_length=500,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "specialization",
                "verbose_name_plural": "specializations",
                "db_table": "specializations",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="idx_spec_name")],
            },
        ),
        migrations.CreateModel(
            name="UserSpecialization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this user-specialization relationship",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        help_text="Specialization that the user has",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialization_users",
                        to="api.specialization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who has this specialization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_specializations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user specialization",
                "verbose_name_plural": "user specializations",
                "db_table": "user_specializations",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's areas of expertise",
                related_name="users",
                through="api.UserSpecialization",
                to="api.specialization",
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the certificate",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Certificate name/title",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        help_text="Organization that issued the certificate",
                        max_length=200,
                        verbose_name="issuer",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        help_text="When the certificate was issued",
                        verbose_name="issue date",
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        help_text="URL link to the certificate (external link)",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="certificate URL",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
                "db_table": "certificates",
                "ordering": ["-issue_date"],
                "indexes": [models.Index(fields=["user"], name="idx_cert_user")],
            },
        ),
        migrations.CreateModel(
            name="PointsWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the wallet",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current points balance (cannot be negative)",
                        verbose_name="balance",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns this wallet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "points wallet",
                "verbose_name_plural": "points wallets",
                "db_table": "points_wallets",
                "indexes": [models.Index(fields=["user"], name="idx_wallet_user")],
            },
        ),
        migrations.AddIndex(
            model_name="userspecialization",
            index=models.Index(fields=["user", "specialization"], name="idx_user_spec"),
        ),
        migrations.AlterUniqueTogether(
            name="userspecialization",
            unique_together={("user", "specialization")},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="idx_user_email"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="idx_user_username"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="idx_user_created"),
        ),
    ]
