# Generated by Django 5.2.5 on 2026-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="specialization_form_completed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the user completed or skipped the specialization form (null = not yet shown)",
                null=True,
                verbose_name="specialization form completed at",
            ),
        ),
    ]
