# Generated by Django 5.2.5 on 2026-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded certificate file (PDF or image, optional if URL provided)",
                null=True,
                upload_to="certificates/%Y/%m/",
                verbose_name="certificate file",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certificate_url",
            field=models.URLField(
                blank=True,
                help_text="External URL link to the certificate (optional if a file is uploaded)",
                max_length=500,
                null=True,
                verbose_name="certificate URL",
            ),
        ),
    ]
