# Generated by Django 5.2.5 on 2026-05-24 15:52

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_certificate_certificate_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=1000)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (45, "45 minutes"),
                            (60, "60 minutes"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "proposed_slots",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateTimeField(),
                        help_text="Up to 5 datetime slots proposed by the asker (UTC).",
                        size=5,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("meet_link", models.URLField(blank=True, max_length=500)),
                ("google_event_id", models.CharField(blank=True, max_length=255)),
                ("decline_message", models.TextField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending answerer response"),
                            ("scheduled", "Scheduled"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled by asker"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_requests",
                        to="api.answer",
                    ),
                ),
                (
                    "answerer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asker", "-created_at"], name="idx_mr_asker_created"
                    ),
                    models.Index(
                        fields=["answerer", "-created_at"],
                        name="idx_mr_answerer_created",
                    ),
                    models.Index(fields=["status"], name="idx_mr_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "scheduled"])),
                        fields=("answer", "asker"),
                        name="uniq_active_meeting_per_asker_per_answer",
                    )
                ],
            },
        ),
    ]
