# Generated by Django 5.2.5 on 2026-06-18 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_meetingrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeenPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seen_posts",
            },
        ),
        migrations.CreateModel(
            name="SeenQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seen_questions",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="answerer",
            field=models.ForeignKey(
                blank=True,
                help_text="The user (meet attendee) who will receive points on resolve.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions_to_explain",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="booked_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="is_blocked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="is_transferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="specialization",
            name="points",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Base point value used for question cost. The cost of a question is max(points) across its specializations + a flat bonus per extra spec.",
                verbose_name="points",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_transferred", False),
                    models.Q(("is_blocked", True), ("answerer__isnull", False)),
                    _connector="OR",
                ),
                name="q_transferred_requires_block_and_answerer",
            ),
        ),
        migrations.AddField(
            model_name="seenpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seen_by",
                to="api.post",
            ),
        ),
        migrations.AddField(
            model_name="seenpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seen_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seenquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seen_by",
                to="api.question",
            ),
        ),
        migrations.AddField(
            model_name="seenquestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seen_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="seenpost",
            index=models.Index(fields=["user", "post"], name="idx_seenp_user_post"),
        ),
        migrations.AlterUniqueTogether(
            name="seenpost",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="seenquestion",
            index=models.Index(
                fields=["user", "question"], name="idx_seenq_user_question"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seenquestion",
            unique_together={("user", "question")},
        ),
    ]
